app:
  cookies:
    domain: localhost
    http-only: true
    max-age: PT720H
    voter-uuid-cookie-name: voterUUID

spring:
  main:
    allow-circular-references: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: sa
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    database_platform: org.hibernate.dialect.H2Dialect
    hibernate:
      format_sql: true
      batchSize: 30
      ddl-auto: none
      implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    locations: classpath:/db/migration,classpath:/db/testdata
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
