name: Build pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'maven-release-plugin')"
    name: Build Maven project
    strategy:
      matrix:
        java: [ 14 ]
    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Set up Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build and test project
        run: mvn -s .m2/settings.xml clean verify
